
development:
  secret_token: <%= ENV["secret_token"] %>
  SECRET_KEY_BASE: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_ACCESS_KEY: <%= ENV["AWS_ACCESS_KEY"] %>
  AWS_SECRET_KEY: <%= ENV["AWS_SECRET_KEY"] %>
  AWS_BUCKET: <%= ENV["AWS_BUCKET"] %>
